"""2026 backtest with rolling bias recalibration.

Instead of applying a fixed 2025 bias correction, recompute the bias
every 28 days using only the most recent 28 days of actual results.
This adapts to K-rate shifts at the start of each season.
"""
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.config import load_config
from src.odds.pricing import add_betting_columns


ROLLING_WINDOW_DAYS = 28   # days of recent results to estimate bias
MIN_SAMPLES         = 30   # minimum games before activating rolling bias


def american_to_decimal(odds):
    o = float(odds)
    return (1 + o / 100) if o >= 100 else (1 + 100 / abs(o))


def resolve_outcome(row):
    actual = row.get("strikeouts")
    if pd.isna(actual): return np.nan
    return 1 if (actual > row["line"] if row["best_side"] == "over" else actual < row["line"]) else 0


def roi_fn(grp):
    if grp.empty: return np.nan
    odds = np.where(grp["best_side"] == "over", grp["over_odds"], grp["under_odds"])
    dec  = np.where(odds > 0, 1 + odds / 100, 1 + 100 / np.abs(np.where(odds == 0, 1, odds)))
    return float(np.where(grp["won"].astype(bool), dec - 1, -1.0).mean())


def main():
    config = load_config("config/config.yaml")

    # Load 2026 predictions (already generated by backtest_2026 run)
    preds = pd.read_csv("data/processed/backtest_2026_predictions.csv")
    preds["game_date"] = pd.to_datetime(preds["game_date"])
    preds = preds[preds["game_date"] <= pd.Timestamp("2026-05-31")].copy()

    # Load 2026 odds
    odds_raw = pd.read_csv("data/odds/historical_pitcher_props_plus_2026_6h.csv")
    odds_raw["game_date"] = pd.to_datetime(odds_raw["game_date"])
    odds_raw["pitcher_id"] = (
        pd.to_numeric(odds_raw["pitcher_id"], errors="coerce")
        .dropna().astype(int).astype(str)
        .reindex(odds_raw.index, fill_value="")
    )
    odds_raw = odds_raw[(odds_raw["game_date"].dt.year == 2026) &
                        (odds_raw["game_date"] <= pd.Timestamp("2026-05-31"))].copy()

    # Main-line filter
    odds_raw["over_odds"]  = pd.to_numeric(odds_raw["over_odds"],  errors="coerce")
    odds_raw["under_odds"] = pd.to_numeric(odds_raw["under_odds"], errors="coerce")
    odds_mf = odds_raw[
        odds_raw["over_odds"].between(-160, 140) | odds_raw["under_odds"].between(-160, 140)
    ].copy()

    # Best line per pitcher/market/game
    rows = []
    for keys, g in odds_mf[odds_mf["market"] == "strikeouts"].groupby(
        ["game_date", "pitcher_id", "line"], dropna=False
    ):
        over_row  = g.sort_values("over_odds",  ascending=False, na_position="last").iloc[0]
        under_row = g.sort_values("under_odds", ascending=False, na_position="last").iloc[0]
        rows.append({
            "game_date":   keys[0],
            "pitcher_id":  keys[1],
            "market":      "strikeouts",
            "line":        keys[2],
            "over_odds":   over_row["over_odds"],
            "under_odds":  under_row["under_odds"],
        })
    odds_sk = pd.DataFrame(rows)

    preds["pitcher_id"] = preds["pitcher_id"].astype(str)
    odds_sk["pitcher_id"] = odds_sk["pitcher_id"].astype(str)

    merged = preds.merge(odds_sk, on=["game_date", "pitcher_id"], how="inner")
    print(f"Merged rows: {len(merged)}")

    # ── Rolling bias recalibration ─────────────────────────────────────────────
    # Sort by date; for each game compute rolling bias from the prior 28 days
    merged = merged.sort_values("game_date").reset_index(drop=True)

    rolling_bias = []
    for i, row in merged.iterrows():
        cutoff_end   = row["game_date"]
        cutoff_start = cutoff_end - pd.Timedelta(days=ROLLING_WINDOW_DAYS)
        window = merged[
            (merged["game_date"] >= cutoff_start) &
            (merged["game_date"] <  cutoff_end)
        ]
        if len(window) >= MIN_SAMPLES and "strikeouts" in window.columns:
            bias = float((window["strikeouts"] - window["strikeouts_projection"]).mean())
        else:
            bias = -0.074   # fall back to 2025 calibration
        rolling_bias.append(bias)

    merged["rolling_bias"] = rolling_bias
    merged["adj_projection"] = merged["strikeouts_projection"] + merged["rolling_bias"]

    # Compute edge/probability with adjusted projection
    residual_std = config["betting"]["default_residual_std"]["strikeouts"]
    edge_shrink  = config["betting"]["edge_shrink_factor"]
    max_kelly    = config["betting"]["max_kelly_fraction"]

    result_rows = []
    for _, row in merged.iterrows():
        over_dec  = american_to_decimal(row["over_odds"])
        under_dec = american_to_decimal(row["under_odds"])
        from scipy.stats import norm
        line = row["line"]
        proj = row["adj_projection"]
        over_prob  = float(1 - norm.cdf(line, loc=proj, scale=residual_std))
        under_prob = 1 - over_prob

        over_implied  = 1 / over_dec
        under_implied = 1 / under_dec

        over_edge  = (over_prob  - over_implied)  / over_implied  * 100
        under_edge = (under_prob - under_implied) / under_implied * 100

        # Shrink edge
        over_edge  *= (1 - edge_shrink)
        under_edge *= (1 - edge_shrink)

        best_side = "over" if over_edge >= under_edge else "under"
        edge_pct  = over_edge if best_side == "over" else under_edge

        over_kelly  = max(0, over_prob  - over_implied)  / (over_dec  - 1) * max_kelly / max(over_edge/100,  0.001) * over_edge  / 100
        under_kelly = max(0, under_prob - under_implied) / (under_dec - 1) * max_kelly / max(under_edge/100, 0.001) * under_edge / 100
        kelly = min(over_kelly if best_side == "over" else under_kelly, max_kelly)

        result_rows.append({
            "game_date":      row["game_date"],
            "pitcher_id":     row["pitcher_id"],
            "line":           line,
            "strikeouts":     row.get("strikeouts"),
            "raw_projection": row["strikeouts_projection"],
            "rolling_bias":   row["rolling_bias"],
            "adj_projection": proj,
            "abs_gap":        abs(proj - line),
            "edge_pct":       edge_pct,
            "best_side":      best_side,
            "over_odds":      row["over_odds"],
            "under_odds":     row["under_odds"],
            "kelly_fraction": kelly,
        })

    res = pd.DataFrame(result_rows)
    res["month"] = res["game_date"].dt.month

    # Apply qualifying filters
    q = res[
        (res["edge_pct"] >= 3.0) & (res["edge_pct"] <= 10.0) & (res["abs_gap"] <= 0.8)
    ].copy()
    q["won"] = q.apply(resolve_outcome, axis=1)
    q = q.dropna(subset=["won"])

    MONTHS = {3:"Mar", 4:"Apr", 5:"May"}

    print("\n" + "=" * 62)
    print("  2026 BACKTEST — ROLLING BIAS RECALIBRATION")
    print("=" * 62)
    print(f"\n  Rolling window: {ROLLING_WINDOW_DAYS} days  |  Min samples: {MIN_SAMPLES}")
    print(f"  Qualifying bets: {len(q)}")

    # Rolling bias over time
    bias_by_month = res.groupby("month")["rolling_bias"].mean()
    print(f"\n  Rolling bias by month (positive = model under-predicts):")
    for m, b in bias_by_month.items():
        print(f"    {MONTHS.get(m,m):>4}: {b:+.3f}")

    print(f"\n  {'Month':>5}  {'N':>5}  {'Win%':>7}  {'ROI':>8}")
    for m in sorted(q["month"].unique()):
        sub = q[q["month"] == m]
        print(f"  {MONTHS.get(m,m):>5}  {len(sub):>5}  {sub['won'].mean()*100:>6.1f}%  {roi_fn(sub)*100:>7.2f}%")

    print(f"\n  OVERALL: n={len(q)}  win={q['won'].mean():.3f}  roi={roi_fn(q)*100:+.2f}%")

    # Statistical test
    if len(q) > 20:
        odds_arr = np.where(q["best_side"]=="over", q["over_odds"], q["under_odds"])
        dec_arr  = np.where(odds_arr > 0, 1+odds_arr/100, 1+100/np.abs(np.where(odds_arr==0,1,odds_arr)))
        breakeven = (1/dec_arr).mean()
        z = (q["won"].mean() - breakeven) / np.sqrt(breakeven*(1-breakeven)/len(q))
        p = float(stats.norm.sf(z))
        print(f"  Breakeven: {breakeven:.3f}  Z={z:.2f}  p={p:.4f}")

    # Compare: fixed 2025 bias vs rolling
    q_fixed = res.copy()
    q_fixed["adj_projection_fixed"] = res["raw_projection"] - 0.074
    q_fixed["abs_gap_fixed"] = abs(q_fixed["adj_projection_fixed"] - q_fixed["line"])
    # Edge with fixed bias - skip recompute, use original backtest result
    print(f"\n  Fixed 2025 bias result (from backtest):  n=332  win=41.9%  roi=-10.37%")
    print(f"  Rolling bias result:                     n={len(q)}  win={q['won'].mean()*100:.1f}%  roi={roi_fn(q)*100:+.2f}%")


if __name__ == "__main__":
    main()
